#!/bin/bash

echo "We will delete all big data files in directory ${PWD}, is that okay?"
read ans

if [ $ans == "1" ]; then

echo "Should we delete Checkpoints too?"
read chkans

if [ $chkans == "1" ]; then
    find . -type d -name "*Checkpoints" -print 2>/dev/null | while read line; do
	echo "Removing folder '$line'"
	rm -rf $line
    done
fi

find . -type d -name "*HyVolumeData" -print 2>/dev/null | while read line; do
    echo "Removing folder '$line'"
    rm -rf $line
done

find . -type d -name "*NeutrinoVolumeData" -print 2>/dev/null | while read line; do
    echo "Removing folder '$line'"
    rm -rf $line
done

find . -type d -name "*GrVolumeData" -print 2>/dev/null | while read line; do
    echo "Removing folder '$line'"
    rm -rf $line
done

else
    echo "Not deleting"
fi
