#!/bin/bash

module load paraview

if [ ! -d "./PNGsForRun/" ]; then
   mkdir PNGsForRun	  
fi

current_path=${PWD}

if [ ! -d "./Run/NeutrinoVolumeData/" ]; then
   echo "Directory ${PWD}/Run/NeutrinoVolumeData does not exist, exiting..."
   exit
fi

cd ./Run/NeutrinoVolumeData/

if [ ! -d "./Eavg_xFromScript" ]; then
   ApplyObservers -t Eavg_x -r Scalar -s=1 -domaininput ../HyDomain.input -o "ConvertToVtk(Input=Eavg_x; Basename=Eavg_xFromScript)" -NoDomainHistory
fi

pvbatch --use-offscreen-rendering /scratch/p/pfeiffer/tvincent/BNS_Disks_project/Scripts/pvslicer.py --pngfile Eavg_x --field Eavg_x --pvdfile Eavg_xFromScript.pvd
cp *.png ${current_path}/PNGsForRun/
rm -rf *Eavg_x*

cd ${current_path}
