#!/bin/bash

module load paraview

if [ ! -d "./PNGsForRun/" ]; then
   mkdir PNGsForRun	  
fi

current_path=${PWD}

if [ ! -d "./Run/HyVolumeData/" ]; then
   echo "Directory ${PWD}/Run/HyVolumeData does not exist, exiting..."
   exit
fi

cd ./Run/HyVolumeData/

if [ ! -d "./YeFromScript" ]; then
   ApplyObservers -t Ye -r Scalar -s=1 -domaininput ../HyDomain.input -o "ConvertToVtk(Input=Ye; Basename=YeFromScript)" -NoDomainHistory
fi

pvbatch --use-offscreen-rendering /scratch/p/pfeiffer/tvincent/BNS_Disks_project/Scripts/pvslicer.py --pngfile Ye --field Ye --pvdfile YeFromScript.pvd
cp *.png ${current_path}/PNGsForRun/
rm -rf *Ye*

cd ${current_path}
