#!/bin/bash

module load paraview

if [ ! -d "./PNGsForRun/" ]; then
   mkdir PNGsForRun	  
fi

current_path=${PWD}

if [ ! -d "./Run/NeutrinoVolumeData/" ]; then
   echo "Directory ${PWD}/Run/NeutrinoVolumeData does not exist, exiting..."
   exit
fi

cd ./Run/NeutrinoVolumeData/

if [ ! -d "./ENuaXZFromScript" ]; then
   ApplyObservers -t ENua -r Scalar -s=1 -domaininput ../HyDomain.input -o "ConvertToVtk(Input=ENua; Basename=ENuaXZFromScript)" -NoDomainHistory
fi

pvbatch --use-offscreen-rendering /scratch/p/pfeiffer/tvincent/BNS_Disks_project/Scripts/pvslicer_neu_minmax.py --nx 0.0 --ny 1.0 --nz 0.0 --min 1e-12 --pngfile ENuaXZ --field ENua --pvdfile ENuaXZFromScript.pvd
cp *.png ${current_path}/PNGsForRun/
rm -rf *ENua*

cd ${current_path}
