#!/bin/bash

module load paraview

if [ ! -d "./PNGsForRun/" ]; then
   mkdir PNGsForRun	  
fi

current_path=${PWD}

if [ ! -d "./Run/NeutrinoVolumeData/" ]; then
   echo "Directory ${PWD}/Run/NeutrinoVolumeData does not exist, exiting..."
   exit
fi

cd ./Run/NeutrinoVolumeData/

if [ ! -d "./FInertialxFromScript" ]; then
   ApplyObservers -t FInertialx -r 1 -d 3 -s=1 -domaininput ../HyDomain.input -o "ConvertToVtk(Input=FInertialx; Basename=FInertialxFromScript)" -NoDomainHistory
fi

pvbatch --use-offscreen-rendering /scratch/p/pfeiffer/tvincent/BNS_Disks_project/Scripts/pvslicer.py --pngfile FInertialx --field FInertialx --pvdfile FInertialxFromScript.pvd
cp *.png ${current_path}/PNGsForRun/
rm -rf *FInertialx*

cd ${current_path}
